config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    resource :profile, only: :show
    resource :session, only: :destroy

    resources :bulletins, only: %i[index show edit update new create] do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      root 'home#index'
      resources :categories, only: %i[index destroy edit update new create]
      resources :bulletins, only: :index do
        member do
          patch 'archive'
          patch 'publish'
          patch 'reject'
        end
      end
    end

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
  end
end

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  - flash.each do |type, msg|
    .alert.alert-dismissible.fade.show class="alert-#{type.to_s}"
      = msg
      button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.me-auto
      = link_to t('.app_name'), root_path, class: 'navbar-brand me-md-4'
      ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
        li.nav-item.me-2
          = link_to t('.home_page'), root_path, class: 'nav-link link-dark'
        - if signed_in?
          .nav-item.me-2.d-flex
            = link_to t('.my_bulletins'), profile_path, class: 'nav-link link-dark'
          .nav-item.me-2.d-flex
            = link_to t('.add_bulletin'), new_bulletin_path, class: 'nav-link link-dark'
    ul.nav.nav-pills
      - if signed_in?
        - if admin?
          .nav-item.me-2.d-flex
            = link_to t('.admin'), admin_root_path, class: 'nav-link link-dark'
          .nav-item.me-2.d-flex
        = link_to t('.sign_out'), session_path, data: { turbo_method: :delete }, class: 'nav-link link-dark'
      - else
        = button_to auth_request_path('github'), method: :post, data: { turbo: false }, class: 'nav-link link-dark' do
          span.bi.bi-github.me-2
          = t('.sign_in')

app/views/layouts/shared/_nav_admin.html.slim
u.nav.flex-column.nav-pills
  li.nav-item
    = link_to t('.moderated'), admin_root_path, class: class_names('nav-link link-dark text-decoration-none', { active: current_page?(admin_root_path) })
    = link_to t('.all_bulletins'), admin_bulletins_path, class: class_names('nav-link link-dark', { active: current_page?(admin_bulletins_path) })
    = link_to t('.all_categories'), admin_categories_path, class: class_names('nav-link link-dark', { active: current_page?(admin_categories_path) })