config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    resource :profile, only: :show
    resource :session, only: :destroy

    resources :bulletins, only: %i[index show edit update new create] do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      root 'home#index'
      resources :categories, only: %i[index destroy edit update new create]
      resources :bulletins, only: :index do
        member do
          patch 'archive'
          patch 'publish'
          patch 'reject'
        end
      end
    end

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
  end
end

app/controllers/web/admin/home_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class HomeController < Web::Admin::ApplicationController
      def index
        @bulletins = Bulletin.under_moderation.order(created_at: :desc).page(params[:page])
      end
    end
  end
end

app/views/web/admin/home/index.html.slim
.container
  .row
    .col-md-3
      = render 'layouts/shared/nav_admin'
    .col-md-9
      h2
        = t('.title')
      .row.mt-2
        table.table.table-borderless
          thead
            tr
              th = t('.name')
              th = t('.publication_date')
              th = t('.actions')
          tbody
            - @bulletins.each do |bulletin|
              tr
                td
                  = link_to bulletin.title, bulletin
                td
                  = distance_of_time_in_words_to_now(bulletin.created_at, highest_measure_only: true)
                td
                  = link_to t('.publish'), publish_admin_bulletin_path(bulletin), data: { turbo_method: :patch, turbo_confirm: t('.confirm_publish') }, class: 'me-1'
                  = link_to t('.reject'), reject_admin_bulletin_path(bulletin), data: { turbo_method: :patch, turbo_confirm: t('.confirm_reject') }, class: 'me-1'
                  - if bulletin.may_archive?
                    = link_to t('.archive'), archive_admin_bulletin_path(bulletin, redirect_to: admin_root_path),
                      data: { turbo_method: :patch, turbo_confirm: t('.confirm_archive') }, class: 'text-danger ms-1'

= paginate @bulletins, theme: 'bootstrap-5',
        pagination_class: 'pagination flex-wrap justify-content-center'