config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    resource :profile, only: :show
    resource :session, only: :destroy

    resources :bulletins, only: %i[index show edit update new create] do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      root 'home#index'
      resources :categories, only: %i[index destroy edit update new create]
      resources :bulletins, only: :index do
        member do
          patch 'archive'
          patch 'publish'
          patch 'reject'
        end
      end
    end

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
  end
end

app/controllers/web/profiles_controller.rb
# frozen_string_literal: true

class Web::ProfilesController < Web::ApplicationController
  def show
    authenticate_user!

    @search_query = current_user&.bulletins&.ransack(params[:q])
    @bulletins = @search_query&.result&.order(created_at: :desc)&.page(params[:page])
  end
end

app/views/web/profiles/_search_panel.html.slim
.p-3.bg-light.border.shadow-sm.rounded-3
  = search_form_for search_query, url: profile_path do |f|
    .row.my-2
      .col-6
        = f.input :title_cont, label: false
      .col-4
        = f.input :state_eq, as: :select,
                  collection: bulletin_states_for_select,
                  label: false
      .col-2
          = f.submit t('search'), class: 'btn btn-primary me-2'
          = link_to t('reset'), url_for, class: 'btn btn-outline-primary'

app/views/web/profiles/show.html.slim
.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-white.rounded-3
      .row
        .p-3.p-lg-5.pt-lg-0
          .mb-4.h2
            = t('.title')
            hr
          .mb-2
            = link_to t('.add_bulletin'), new_bulletin_path
          = render 'search_panel', search_query: @search_query
          .row.mt-2
            table.table.table-borderless
              thead
                tr
                  th
                    = t('.name')
                  th
                    = t('.state')
                  th
                    = t('.publication_date')
                  th
                    = t('.actions')
              tbody
                - @bulletins.each do |bulletin|
                  tr
                    td
                      = bulletin.title
                    td
                      = t(bulletin.state.to_s)
                    td
                      = distance_of_time_in_words_to_now(bulletin.created_at, highest_measure_only: true)
                    td
                      = link_to t('.show'), bulletin
                      = link_to t('.edit'), edit_bulletin_path(bulletin), class: 'ms-2'
                      - if bulletin.may_to_moderate?
                        = link_to t('.to_moderate'), to_moderate_bulletin_path(bulletin), data: { turbo_method: :patch }, class: 'ms-2'
                      - if bulletin.may_archive?
                        = link_to t('.archive'), archive_bulletin_path(bulletin), class: 'ms-2 text-danger', data: { turbo_method: :patch, turbo_confirm: t('.confirm') }

= paginate @bulletins, theme: 'bootstrap-5',
        pagination_class: 'pagination flex-wrap justify-content-center'